// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhvKqzs39jY8klJUGHNDAti0nNXOHXZo8',
    appId: '1:22831227127:web:11a916495470cc9a8833f2',
    messagingSenderId: '22831227127',
    projectId: 'trail-share-4ff3e',
    authDomain: 'trail-share-4ff3e.firebaseapp.com',
    storageBucket: 'trail-share-4ff3e.firebasestorage.app',
    measurementId: 'G-3578QCRXNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4SeZSNMoTi2yrLhADX0NA7N8FVUW0gE8',
    appId: '1:22831227127:android:89936299d4ce268d8833f2',
    messagingSenderId: '22831227127',
    projectId: 'trail-share-4ff3e',
    storageBucket: 'trail-share-4ff3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUF_Lu8n3xndxiVMH4aRawwP-T75m9Qu8',
    appId: '1:22831227127:ios:13ebcb0010617ce98833f2',
    messagingSenderId: '22831227127',
    projectId: 'trail-share-4ff3e',
    storageBucket: 'trail-share-4ff3e.firebasestorage.app',
    iosBundleId: 'com.example.trailShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUF_Lu8n3xndxiVMH4aRawwP-T75m9Qu8',
    appId: '1:22831227127:ios:13ebcb0010617ce98833f2',
    messagingSenderId: '22831227127',
    projectId: 'trail-share-4ff3e',
    storageBucket: 'trail-share-4ff3e.firebasestorage.app',
    iosBundleId: 'com.example.trailShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhvKqzs39jY8klJUGHNDAti0nNXOHXZo8',
    appId: '1:22831227127:web:1d05f3ca2da6a0728833f2',
    messagingSenderId: '22831227127',
    projectId: 'trail-share-4ff3e',
    authDomain: 'trail-share-4ff3e.firebaseapp.com',
    storageBucket: 'trail-share-4ff3e.firebasestorage.app',
    measurementId: 'G-G8MRP7Q5LQ',
  );
}
